# Generated by Django 4.2.28 on 2026-06-04 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('stage', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pickems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_A', to='banter.team')),
                ('group_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_B', to='banter.team')),
                ('group_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_C', to='banter.team')),
                ('group_D', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_D', to='banter.team')),
                ('group_E', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_E', to='banter.team')),
                ('group_F', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_F', to='banter.team')),
                ('group_G', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_G', to='banter.team')),
                ('group_H', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_H', to='banter.team')),
                ('group_I', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_I', to='banter.team')),
                ('group_J', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_J', to='banter.team')),
                ('group_K', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_K', to='banter.team')),
                ('group_L', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_L', to='banter.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banter.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
